name: 🚀 Feature Story
description: Create a new feature story for development
title: "[FEATURE] "
labels: ["type/feature", "status/todo", "claude-code/ready"]
projects: ["kubesec-io/1"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🎯 Feature Story Template
        
        Use this template to create structured feature stories that can be easily picked up by Claude Code or team members.

  - type: input
    id: story_title
    attributes:
      label: Story Title
      description: Brief, descriptive title for the feature
      placeholder: "As a user, I want to..."
    validations:
      required: true

  - type: textarea
    id: user_story
    attributes:
      label: User Story
      description: Complete user story with acceptance criteria
      placeholder: |
        **As a** [user type]
        **I want** [functionality]
        **So that** [benefit/value]
        
        ### Acceptance Criteria
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: textarea
    id: technical_requirements
    attributes:
      label: Technical Requirements
      description: Technical specifications and constraints
      placeholder: |
        ### Architecture Considerations
        - Component affected: 
        - New dependencies:
        - Performance requirements:
        - Security considerations:
        
        ### Implementation Notes
        - API changes:
        - Database changes:
        - Configuration changes:
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Story priority level
      options:
        - priority/low
        - priority/medium
        - priority/high
        - priority/critical
      default: 1
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Complexity
      description: Development complexity estimate
      options:
        - complexity/low
        - complexity/medium
        - complexity/high
      default: 1
    validations:
      required: true

  - type: dropdown
    id: story_points
    attributes:
      label: Story Points
      description: Effort estimation in story points
      options:
        - "1"
        - "2"
        - "3"
        - "5"
        - "8"
        - "13"
        - "21"
      default: 2
    validations:
      required: true

  - type: textarea
    id: definition_of_done
    attributes:
      label: Definition of Done
      description: Checklist for story completion
      value: |
        ### Definition of Done Checklist
        - [ ] Code implemented and reviewed
        - [ ] Unit tests written and passing
        - [ ] Integration tests passing
        - [ ] Security scan passing
        - [ ] Documentation updated
        - [ ] Manual testing completed
        - [ ] Performance requirements met
        - [ ] Accessibility requirements met (if applicable)
        - [ ] Ready for deployment
    validations:
      required: true

  - type: textarea
    id: related_issues
    attributes:
      label: Related Issues & Dependencies
      description: Links to related issues or blocking dependencies
      placeholder: |
        ### Related Issues
        - Relates to #
        - Blocks #
        - Blocked by #
        
        ### Dependencies
        - External dependency:
        - Internal dependency:

  - type: textarea
    id: claude_context
    attributes:
      label: Claude Code Context
      description: Additional context for Claude Code pickup
      placeholder: |
        ### For Claude Code Implementation
        
        **Key Files to Review:**
        - 
        - 
        
        **Architecture Decisions:**
        - 
        - 
        
        **Testing Strategy:**
        - 
        
        **Security Considerations:**
        - 
        
        **Integration Points:**
        - 

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Pre-implementation requirements
      options:
        - label: Architecture review completed
        - label: Security review completed
        - label: Performance requirements defined
        - label: API design approved
        - label: Dependencies identified and approved
        - label: Database schema changes reviewed (if applicable)

  - type: markdown
    attributes:
      value: |
        ---
        
        ## 📋 Next Steps
        
        1. **Triage**: Product owner will review and prioritize
        2. **Planning**: Technical lead will review architecture
        3. **Assignment**: Story will be assigned to developer or Claude Code
        4. **Implementation**: Development begins following technical requirements
        5. **Review**: Code review and testing phases
        6. **Deployment**: Production deployment following CI/CD pipeline
        
        **Note for Claude Code**: This story format is optimized for AI pickup with all necessary context and clear acceptance criteria.